
# Site settings
title: Andrew C. Martin
email: andy@acm.im
description: > # this means to ignore newlines until "baseurl:"
  An an environmental scientist from the Isle of Man, with interests in technology, 
  long-term ecology, and biodiversity, currently at Oxford University.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://acm.im" # the base hostname & protocol for your site
twitter_username: iomandrew
github_username:  AndrewIOM
profile_pic: "head.jpeg"
sidebar_background: "leaves.jpg"

# Build settings
markdown: kramdown
